image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_HML: caleberios/gaia-local:homolog
  LATEST_VER_PROD: caleberios/gaia-local:latest

stages:
  - build
  - quality
  - pushImage
  - deploy

installDependencies:
  stage: build
  image: node:alpine
  script:
    - npm install

buildLocal:
  stage: build
  script:
    - docker build .

testCheck:
  stage: quality
  image: node:alpine
  script:
    - npm install
    - npm test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  
staticAnalysis:
  stage: quality
  image: node:alpine
  script:
    - npm install
    - npm run lint

pushHomolog:
  stage: pushImage
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_HML .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_HML && docker image rm $LATEST_VER_HML

pushProd:
  stage: pushImage
  only:
    - master
  script:
    - docker build -t $LATEST_VER_PROD .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_PROD && docker image rm $LATEST_VER_PROD

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete svc gaia-local-hml
    - kubectl delete deployments gaia-local-hml
    - cat k8s/gaia_local_hml.yaml | sed "s/{{API_KEY}}/$API_KEY/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete svc gaia-local
    - kubectl delete deployments gaia-local
    - cat k8s/gaia_local.yaml | sed "s/{{API_KEY}}/$API_KEY/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -
