version: '3'

services:
  gaialocal:
    build: .
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - ENVIRONMENT=dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=gaialocal
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=gaialocal
      - MONGODB_APPLICATION_USER=aashrey
      - MONGODB_APPLICATION_PASS=admin123
    ports: 
      - 27017:27017