version: '3'

services:
  gaialocal:
    build: .
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - ENVIRONMENT=dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: aashreys/mongo-auth:latest
    command: mongod --port 27017
    ports: 
      - 27017:27017
